### ISSUE TITLE
[cz] localization error for remotes

### ISSUE THREAD

**Issue by nerakhon** [microsoft/vscode-loc#1317]
In english in remote explorer there are 4 options:

```
EN --> CZ

Dev Containers --> Dev Containers (non-localized but OK)
WSL Targets --> Cíle WSL
Remote --> Vzdálená pošta !!! Which is a nonsesne that means remote mail
Remote Repositories - Vzdálená uložiště

```
I'd propose the following fix (cant' find it in the loc project so I guess it has to happen somewhere else)

```
EN --> CZ

Dev Containers --> Dev Containers (non-localized but OK)
WSL Targets --> Cíle WSL
Remote --> Vzdálená uložiště (because that's what they really are exact translation is Remote storages)
Remote Repositories - Vzdálené repozitáře (Remote repositories exact translation)
```

Hope this can be easily fixed.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 813932).

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 there are 3 issues here:

* `Dev Containers --> Dev Containers (non-localized but OK)` - the Dev Containers extension _just today_ onboarded to localization, so that should be updated soon no need to handle that specially
* `Remote --> Vzdálená pošta !!! Which is a nonsesne that means remote mail` - The resource is [here](https://github.com/microsoft/vscode-extensions-loc/blob/e39676197fb2a89370c86c890e310dfedcbdf015/loc/cs/ms-vscode.remote-explorer/ms-vscode.remote-explorer.xlf.lcl#L133)
* `Remote Repositories - Vzdálená uložiště`  - The resource is [here](https://github.com/microsoft/vscode-extensions-loc/blob/e39676197fb2a89370c86c890e310dfedcbdf015/loc/cs/ms-vscode.remote-repositories/ms-vscode.remote-repositories-new.xlf.lcl#L669-L675)

**Comment by cristianosuzuki77** [comment]
Fix on the way to be pushed back.
