### ISSUE TITLE
[de] wrong translation for "Block" in ms-vscode.js-debug

### ISSUE THREAD

**Issue by SirLefti** [microsoft/vscode-loc#1341]
I spotted a misleading translation in the JS debugger, located in the german `ms-vscode.js-debug.i18n.json`.

```
"Block":
de wrong: "Blockieren" // translation of block as a verb
de correct: "Block"    // translation of block as a noun
```
It is just `Block`, because it is not a verb here. Refer to the translations of `Catch Block` and `With Block`, which are correctly translated as `Catch-Block` and `With-Block`.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 822494).

**Comment by v-mholloway** [comment]
@SirLefti Can you please provide more information to track down the resource in question...
a link to the file?
the resource identifier?

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Could you help narrowing down where this is coming to loc?

**Comment by TylerLeonhardt** [comment]
It's here: https://github.com/microsoft/vscode-extensions-loc/blob/7ab75c1159651b218d959079e28f602db498f3b2/src/en/ms-vscode.js-debug/ms-vscode.js-debug-new.xlf#L40-L42

but it seems like js-debug may have accidentally deleted its `bundle` file... because I don't see it [here](https://github.com/microsoft/vscode-extensions-loc/blob/main/src/en/ms-vscode.js-debug/ms-vscode.js-debug-new.xlf).  I'll figure out why that happened but maybe what I sent you there is enough to track down the string.

**Comment by SirLefti** [comment]
It appears to be fixed now.
