### ISSUE TITLE
Please help me Merge the PR

### ISSUE THREAD

**Issue by sam951013** [microsoft/vscode-loc#1531]
Please help me Merge the PR thanks.
#1529
```[tasklist]
### Tasks
```

**Comment by sam951013** [comment]
This is a translation error.

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 933436).

**Comment by crsuzukimsft** [comment]
Hello @sam951013 Per readme, you'd need to open an issue ticket with the suggestion for updating the translation, rather than making direct changes to the translation.
Could you open an issue ticket with the following:
a. Current translation
b. resource name, if you know.
c. Suggested new translation
d. Reason for the suggestion.
