### ISSUE TITLE
ja: "FILE: アクティブ ファイルを比較しています..." -> "FILE: アクティブ ファイルを比較します..."

### ISSUE THREAD

**Issue by wraith13** [microsoft/vscode-loc#156]
`File: Compare Active File With...` コマンドの日本語訳が `FILE: アクティブ ファイルを比較しています...` になっていますが、ここは `FILE: アクティブ ファイルを比較します...` であるべきではないでしょうか？

**Comment by janbaltus** [comment]
@wraith13 please provide screenshot for this issue.

**Comment by wraith13** [comment]
![image](https://user-images.githubusercontent.com/645907/79195094-a64d3e00-7e68-11ea-8030-524171a463cd.png)
Is this all right?

**Comment by janbaltus** [comment]
Thank you!

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Will be fixed in next release.

SRCs:
Compare Active File with Saved
Compare Active File With...
Compare Active File with Saved
Compare Active File with Clipboard
Compare Active File With...
Compare Active File with

Approved TGTs:
保存済みファイルとアクティブ ファイルを比較
アクティブ ファイルを比較...
保存済みファイルとアクティブ ファイルを比較
クリップボードとアクティブ ファイルを比較
アクティブ ファイルを比較...
クリップボードとアクティブ ファイルを比較
