### ISSUE TITLE
[ES] Translation error in Source Control menu

### ISSUE THREAD

**Issue by moxwel** [microsoft/vscode-loc#158]
In the Source Control menu, the buttons **_"Open folder"_** and **_"Clone repository"_** are translated to **_"Aba carpeta"_** and **_"Clone repositorio"_** in Spanish, both of which are wrong.

The best translation are **_"Abrir carpeta"_** and **_"Clonar repositorio"_** respectively.

> Original
![image](https://user-images.githubusercontent.com/49621788/79603546-8f9e2580-80ba-11ea-8789-c8c4163004b2.png)

> Translated to Spanish
![image](https://user-images.githubusercontent.com/49621788/79602968-75b01300-80b9-11ea-8680-397a678e628a.png)

**Comment by lukaschal** [comment]
On review.

File: vscode-extensions\git.xlf
ID: 0; "extensions/git/package.view.workbench.scm.empty"

SRC: In order to use git features, you can open a folder containing a git repository or clone from a URL.\n[Open Folder](command:vscode.openFolder)\n[Clone Repository](command:git.clone)\nTo learn more about how to use git and source control in VS Code [read our docs](https://aka.ms/vscode-scm).

TGT: Para utilizar las características de git, puede abrir una carpeta que contenga un repositorio git o clonarlo desde una dirección URL.\n[Aba carpeta](command:vscode.openFolder)\n[Clone repositorio](command:git.clone)\nPara obtener más información sobre cómo usar Git y el control de código fuente en VS Code [lea nuestros documentos](https://aka.ms/vscode-scm).

**Comment by lukaschal** [comment]
Fixed as suggested.

Para utilizar las características de Git, puede abrir una carpeta que contenga un repositorio Git o clonarlo desde una dirección URL.\nAbrir carpeta\nClonar repositorio\nPara obtener más
información sobre cómo usar Git y el control de código fuente en VS Code, lea nuestros documentos.

**Comment by jisbert** [comment]
_**"Clonar repositorio"**_ and  _**"Abrir carpeta"**_, as suggested by @moxwell, is more idiomatic in Spanish and more accurate translation than _"Clone repositorio"_ and _"Abra carpeta"_.
