### ISSUE TITLE
npm设置无效

### ISSUE THREAD

**Issue by startdawn** [microsoft/vscode-loc#216]
Issue Type: <b>Bug</b>

点开设置，扩展，npm【从资源管理器上下文菜单中启用运行文件夹包含的NPM脚本】设置无效

Extension version: 1.55.2
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.14393

**Comment by v-mholloway** [comment]
@startdawn can you provide more information (in english) as to the issue here.
could you use this template if possible...
Culture: *****
String Identifier: ***** (e.g. notebookActions.executeAbove)
English String: *****
Current Translation: *****
Requested Translation: ****
Screen Shot: ***** (when applicable)

**Comment by danyeh** [comment]
This repo only take feedback of 'translation'. For functionality issue, please create in vscode repo.
