### ISSUE TITLE
Installing vscode-loc on Linux using VSIX Package goes wrong 

### ISSUE THREAD

**Issue by L-IU** [Microsoft/vscode-loc#39]
### Installation error 

> **Alert**: 
>>"Unable to install Extension 'ms-ceintl.vscode-language-pack-zh-hans-1.29.0' as it is not compatible with Code '1.28.2'." 
>>
>---

**Comment by danyeh** [comment]
Thank you @L-IU for the feedback! This is by design behavior if you download from Marketplace because the latest VSIX Package has bigger than VS Code version setting.
Right route is to search language Pack within your VS Code Extension view and click install. Marketplace will auto fall back to the language pack version matches your VS Code version.
![image](https://user-images.githubusercontent.com/19785531/47446559-58beac00-d770-11e8-9637-d17aecca3153.png)
The Marketplace API link does support to download previous version, but need to know extract link. For example, https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-CEINTL/vsextensions/vscode-language-pack-zh-hans/1.28.2/vspackage

**Comment by L-IU** [comment]
Thank you! ^_^
