### ISSUE TITLE
please add keywords property to each language package `package.json`

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-loc#714]
so that we could search by those keyword.
nowadays, we even could not search chinese-languase-packaage by `中文` 
that is inconceivable,

![image](https://user-images.githubusercontent.com/1876302/152086113-2d2f5ec4-6887-43df-89a5-553b6735e2af.png)

all the language-package could be searched only by the package-name within whole-word-match

vscode has provide the `keywords `property to deal with 

see https://code.visualstudio.com/api/references/extension-manifest#fields
![image](https://user-images.githubusercontent.com/1876302/152086426-324bb6f3-4bcd-4f23-9aac-71aeb304c960.png)

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Not sure what loc could do here.

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 can you do me a favor? For each language we support, can you give me the name of the language in the language? Like 中文 for Chinese. We can then add these translations to the keywords in the package.json in each language pack so that when users search for the language in their language, it will show up in search results.

**Comment by cristianosuzuki77** [comment]
@TylerLeonhardt Could you share an example of how this approach?

**Comment by TylerLeonhardt** [comment]
@cristianosuzuki77 in this file:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/package.json
in each language pack, we can add `"keywords": [ "..." ]` we can put the name of the language it's language and then when the user searches for that in the Extension Marketplace, the extension will show up because it's listed as a keyword.

**Comment by cristianosuzuki77** [comment]
If I'm correct, for this to work, a resource similar to"keywords:["target language"]" would need to be present in the localized package.json.
However it seems not trivial and fail-safe way to control how "target language" is translated. It could be literally translated as such.
Since the language is part of the json via "localizedLanguageName": "中文(简体)", would the build be capable to create the keywords attribute instead?

**Comment by TylerLeonhardt** [comment]
It seems like the problem is because the [`localizedLanguageName`](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/package.json#L24) is `中文(简体)` and not just `中文`. If I search for `中文(简体)` I get the language pack, but I don't get it for `中文`.

But then again, if I try another language like Japanese, we have `日本語` in the `localizedLanguageName` but when I search for that in the Extension pane no language pack shows up at all...

@sandy081, is there anything we can do here to make these language packs more discoverable?

**Comment by TylerLeonhardt** [comment]
Also @isidorn as maybe the Marketplace needs some work here.

**Comment by isidorn** [comment]
Extension search needs to be improved. The marketplace does not index the whole extension description, only the short description and the title. So it might be that the string which you searched for is simply not part of the indexed attributes. Hopefully that will change in the future.

**Comment by TylerLeonhardt** [comment]
@isidorn is there any kind of workaround? We were thinking about putting the language name in the `keywords`. Does that help at all in search?

**Comment by isidorn** [comment]
@TylerLeonhardt I believe it should.
@prashantvc can you confirm if the keywords get indexed for search?

**Comment by isidorn** [comment]
Yes the `keywords` will get indexed by search. `keywords` get transitioned to `tags` which search on the Marketplace side indexes.

**Comment by TylerLeonhardt** [comment]
Ok! @isidorn I have a PR out that adds the localized language name to the keywords of each extension. ^^
