### ISSUE TITLE
VSCode / Arabic Language

### ISSUE THREAD

**Issue by Alrusayni** [microsoft/vscode-loc#893]
Hi,

I love to contribute to adding the Arabic language . I'm an Arabic fluent Speak/Write. Also, I'm a Computer science, web developer, and programmer.

I'm ready to handle this project until it gets done.

Please advise.

Thanks

**Comment by csigs** [comment]
Thank you for your feedback. We are currently reviewing it (reference 635634).

**Comment by cristianosuzuki77** [comment]
Thank you both in advance. We're reviewing the next set of languages for expansion and will consider this feedback.

**Comment by PeterNjeim** [comment]
> Thank you for your feedback. We are currently reviewing it (reference 635634).

@csigs may I ask what this reference number refers to? Is it a public reference or only internal for employees.

@cristianosuzuki77 I would like to know the progress, if any, on the choice of the next set of languages to support, if it's allowed to be shared publicly.

Adding RTL support for the UI of VSCode will probably be a large task, maybe some extensions would need to be updated to not hardcode "left" and "right" and instead use "start" and "end" (though I've never written an extension so I don't know if this practice even exists), and various other design choices. VSCode itself is quite modular in its UI already but lots of things would need to move, like the arrow on the left of folders in the Explorer pane would need to be moved to the right side of the folder name in an RTL layout. I believe RTL layout has been asked for since 2016 in the vscode repo, I would like to know if there is actually a push for this feature or if it will be put on the backlog again (this is the "Milestone" it is in right now in the vscode repo). Thanks in advance.

**Comment by soroshsabz** [comment]
@cristianosuzuki77 Any update? where is the reference? is VSCode support RTL languages fundamentally?

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/vscode/issues/11770
